apiVersion: v1
kind: Service
metadata:
  name: apiserver
spec:
  selector:
    app: apiserver
  type: ClusterIP
  clusterIP: None # headless
  ports:
    - name: ingress
      protocol: TCP
      port: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      initContainers:
      - name: setup
        image: node:10.16.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /app
            name: runtime
          - mountPath: /scratch
            name: scratch
        env:
          - name: MESH_ENVIRONMENT
            value: live
          - name: MESH_PROVIDER
            value: apiserver
          - name: MESH_CONTROL_PLANE_ADDRESS
            value: "bowser.default.svc.cluster.local"
        command: ["/bin/bash", "/app/init.sh"]
      containers:
      - name: service
        image: node:10.16.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /app
            name: runtime
          - mountPath: /scratch
            name: scratch
        env:
          - name: MESH_ENVIRONMENT
            value: live
          - name: MESH_PROVIDER
            value: apiserver
          - name: MESH_CONTROL_PLANE_ADDRESS
            value: "bowser.default.svc.cluster.local"
          - name: MESH_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MESH_NODE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command: ["sh", "-c"]
        args: ['DEBUG="*" node /app/build/apiserver.js /app']
        # readinessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:8081"]
        #   initialDelaySeconds: 1
        # livenessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:8081"]
        #   initialDelaySeconds: 1
      - name: envoy
        image: envoyproxy/envoy-alpine:v1.10.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /scratch
            name: scratch
        env:
          - name: K_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: K_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command: ["sh", "-c"]
        args: ["envoy -c /scratch/envoy-sidecar.yaml --service-node ${K_POD_NAMESPACE}_${K_POD_NAME} --service-cluster default"]
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.14.0
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        command:
          - "/go/bin/agent-linux"
          - "--collector.host-port=jaeger-collector.default.svc.cluster.local:14267"
        resources:
          limits:
            memory: 50M
            cpu: 100m
          requests:
            memory: 50M
            cpu: 100m
      volumes:
      - name: runtime
        hostPath:
          path: /Users/wcj/dev/mesh/gitops
      - name: scratch
        emptyDir: {}
