apiVersion: kubedb.com/v1alpha2
kind: MySQL
metadata:
  name: mysql
spec:
  version: "5.7.31"
  terminationPolicy: "WipeOut"
  storageType: "Durable"
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  podTemplate:
    spec:
      args:
      - --character-set-server=utf8mb4
      - --default-time-zone=+00:00
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
