apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: redis
  namespace: development
spec:
  version: 5.0.3-v1
  mode: Standalone
  storageType: Durable
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  podTemplate:
    spec:
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
