apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clusterapp.volumeConfigMap" . }}
  labels:
    {{- include "clusterapp.labels" . | nindent 4 }}
data:
  envoyBootstrap: |
    {{- include "envoyBootstrap" . | indent 4 }}
